database:
  driverClass: org.postgresql.Driver
  user: morpheus
  password: findneo
  url: jdbc:postgresql://postgres:5432/sre-lab
  maxWaitForConnection: 1s
  validationQuery: "/* Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.jdbc.batch_sze: 100
    hibernate.order_inserts: true
    hibernate.order_updates: true
    hibernate.generate_statistics: false

logging:
  appenders:
    - type: console
      layout:
        type: json

server:
  requestLog:
    appenders:
      - type: console
        layout:
          type: access-json

metrics:
  reporters:
    - type: statsd
      host: localhost
      port: 8125