apiVersion: v1
kind: Service
metadata:
  name: users-api
  labels:
  {{- include "users-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.usersApi.type }}
  selector:
    app: users-api
  {{- include "users-api.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.usersApi.ports | toYaml | nindent 2 -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  labels:
  {{- include "users-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.usersApi.replicas }}
  selector:
    matchLabels:
      app: users-api
    {{- include "users-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: users-api
      {{- include "users-api.selectorLabels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - env:
        - name: PORT
          value: {{ quote .Values.usersApi.usersApi.env.port }}
        - name: SERVICE_NAME
          value: {{ quote .Values.usersApi.usersApi.env.serviceName }}
        - name: INSECURE_MODE
          value: {{ quote .Values.usersApi.usersApi.env.insecureMode }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ quote .Values.usersApi.usersApi.env.otelExporterOtlpEndpoint }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.usersApi.usersApi.image.repository }}:{{ .Values.usersApi.usersApi.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.usersApi.usersApi.imagePullPolicy }}
        livenessProbe:
          httpGet:
            path: /health
            port: 9996
          initialDelaySeconds: 3
          periodSeconds: 3
        name: users-api
        ports:
        - containerPort: 9996
        resources: {}