name: Orders API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    container: gradle:7.4-jdk17
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: orders-api

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: gradle build --no-daemon